# https://docs.netlify.com/routing/redirects/



# Added 2022-05-25 - Changed canonical domain to www.stevens.pro for easy sharing.
[[redirects]]
    from = "https://greg.stevens.pro/*"
    to = "https://www.stevens.pro/:splat"
    status = 301
    force = true

# [[redirects]]
#     from = "http://greg.stevens.pro"
#     to = "https://www.stevens.pro"
#     status = 303
#     force = true

[[redirects]]
    # Added 2022-05-25
    from = "http://www.career.stevens.pro/*"
    to = "https://career.stevens.pro/:splat"
    status = 301
    force = true

# Added 2022-05-25
[[redirects]]
    from = "https://main--greg-stevens-pro.netlify.app/*"
    to = "https://www.stevens.pro/:splat"
    status = 301
    force = true    # COMMENT: ensure that we always redirect

# 2022-09-08
[[redirects]]
    from = "/yt"
    to = "https://www.youtube.com/channel/UCEOR5OVIgWpsRVZcoyz8i0Q"
    status = 301
    force = true

# 2022-09-08
[[redirects]]
    from = "/YouTube"
    to = "/yt"
    status = 301
    force = true

# 2022-09-08
[[redirects]]
    from = "/youtube"
    to = "/yt"
    status = 301
    force = true

